from enum import Enum

class Intent(str, Enum):
    DELIVERY_DELAY = "DELIVERY_DELAY"
    MISSING_PACKAGE = "MISSING_PACKAGE"
    ACCOUNT_PAYMENT_ISSUE = "ACCOUNT_PAYMENT_ISSUE"
    CANCELLATION_REFUND = "CANCELLATION_REFUND"
    PRODUCT_INQUIRY = "PRODUCT_INQUIRY"
    POSITIVE_FEEDBACK = "POSITIVE_FEEDBACK"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
